http_port 3128
acl SSL_ports port 443
acl Safe_ports port 80 443
acl CONNECT method CONNECT
acl approved_domains dstdomain "/etc/squid/approved-domains"
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow approved_domains
http_access deny all
cache deny all
